import BlogCard from "@/components/Blog/BlogCard";
import Breadcrumb from "@/components/Common/Breadcrumb/Breadcrumb";
import Container from "@/components/Common/Container";
import Col from "@/components/Common/Grid/Col";
import Flex from "@/components/Common/Grid/Flex";
import Layout from "@/components/Layouts/Layout";
import tokens from "@/config/tokens";
import { toJalali } from "@/helpers/date";
import useIsMobile from "@/hooks/useIsMobile";
import {
  Body1,
  Body2,
  Caption1,
  Divider,
  Title3,
  makeStyles,
  shorthands,
} from "@fluentui/react-components";
import axios from "axios";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import styled from "styled-components";

type Props = {
  footerInfo: FooterInfo;
  navigation: Menu[];
  blog: Blog;
};
export default function Blog(props: Props) {
  const { footerInfo, navigation, blog } = props;
  const { title, slug, image, category_id, readDuration, createdAt, text } =
    blog.attributes;
  const isMobile = useIsMobile();
  const styles = useStyles();

  const breadcrumbItems = [
    { label: "صفحه نخست", link: "/" },
    { label: "بلاگ", link: "/blog" },
    { label: title, link: slug },
  ];

  return (
    <Layout footerInfo={footerInfo} navigation={navigation}>
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <Container>
        <Container>
          <Flex style={{ padding: `${tokens.spacingVerticalXXXL} 0` }}>
            <Col size={9}>
              <Wrapper>
                <Flex gap={24} column>
                  <Breadcrumb justify="start" items={breadcrumbItems} />
                  <Flex gap={24}>
                    {image?.data?.attributes?.formats?.thumbnail && (
                      <img
                        src={`https://admin.protopie.ir${image.data.attributes.formats.thumbnail.url}`}
                        alt={title}
                        width={150}
                        height={150}
                        className={styles.img}
                      />
                    )}
                    <Flex column justify="evenly" style={{ minWidth: "auto" }}>
                      <Body1>{category_id.data.attributes.category}</Body1>
                      <Title3>{title}</Title3>
                      <Flex gap={44}>
                        <Caption1
                          className={styles.readDuration}
                        >{`زمان مطالعه ${readDuration} دقیقه`}</Caption1>
                        <Caption1 className={styles.readDuration}>
                          {toJalali(createdAt)}
                        </Caption1>
                      </Flex>
                    </Flex>
                  </Flex>
                </Flex>
                <Divider className={styles.customLineColor} />
                <Pre>{text}</Pre>
              </Wrapper>
            </Col>
            <Col size={3}>
              <Wrapper>
                <Body2 color={tokens.colorNeutralForeground3}>
                  فهرست محتوا
                </Body2>
              </Wrapper>
            </Col>
          </Flex>
        </Container>
        <Space isMobile={isMobile} />
      </Container>
    </Layout>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const { slug } = context.query;

    const [navigation, blog, footerInfo] = await Promise.all([
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/navigation"),
      axios.get(
        `${process.env.NEXT_PUBLIC_APP_BASEURL}/api/blogs?filters[slug][$eq]=${slug}&populate=*`
      ),
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/footer"),
    ]);

    return {
      props: {
        footerInfo: footerInfo.data,
        navigation: navigation.data,
        blog: blog.data,
      },
    };
  } catch (error) {
    return;
  }
}

const Pre = styled.pre`
  white-space: break-spaces;
  font-family: "YekanBakh";
  line-height: 2rem;
  padding: ${tokens.spacingVerticalXXL} 0;
`;

const Space = styled.div<{ isMobile: boolean }>`
  height: ${(props) => (props.isMobile ? "20px" : "200px")};
  background-image: ${(props) =>
    props.isMobile ? "initial" : "url(images/lines.png)"};
  margin: ${tokens.spacingVerticalXXXL} 0;
}
`;
const Wrapper = styled.div`
  border-radius: ${tokens.borderRadiusMedium};
  background: ${tokens.colorNeutralBackground2};
  padding: ${tokens.spacingVerticalXXL};
}
`;

const useStyles = makeStyles({
  customLineColor: {
    "::before": {
      ...shorthands.borderColor(tokens.colorNeutralBackground2Pressed),
    },
    "::after": {
      ...shorthands.borderColor(tokens.colorNeutralBackground2Pressed),
    },
    marginTop: tokens.spacingVerticalXXL,
  },
  img: {
    ...shorthands.borderRadius(tokens.spacingVerticalS),
  },
  readDuration: {
    color: tokens.colorNeutralForeground4,
    fontFamily: "YekanBakhFaNum",
  },
});
