import BlogContent from "@/components/Blog/BlogContent";
import BlogContentList from "@/components/Blog/BlogContentList";
import BlogHeader from "@/components/Blog/BlogHeader";
import Container from "@/components/Common/Container";
import Col from "@/components/Common/Grid/Col";
import Flex from "@/components/Common/Grid/Flex";
import Layout from "@/components/Layouts/Layout";
import tokens from "@/config/tokens";
import useIsMobile from "@/hooks/useIsMobile";
import {
  Accordion,
  AccordionHeader,
  AccordionItem,
  AccordionPanel,
  Body2,
  Divider,
  makeStyles,
  shorthands,
} from "@fluentui/react-components";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import axios from "axios";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import styled from "styled-components";

type Props = {
  footerInfo: FooterInfo;
  navigation: Menu[];
  blog: Blog;
};
export default function Blog(props: Props) {
  const { footerInfo, navigation, blog } = props;
  const { title, text, anchors } = blog.attributes;

  const isMobile = useIsMobile();
  const styles = useStyles();

  return (
    <Layout footerInfo={footerInfo} navigation={navigation}>
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <Container>
        <Container>
          <Flex
            style={{ padding: `${tokens.spacingVerticalXXXL} 0` }}
            column={isMobile}
          >
            <Col size={isMobile ? 12 : 9}>
              {isMobile ? (
                <>
                  <Wrapper style={{ marginBottom: tokens.spacingVerticalXXXL }}>
                    <BlogHeader blog={blog.attributes} />
                  </Wrapper>

                  <Wrapper style={{ marginBottom: tokens.spacingVerticalXXXL }}>
                    <BlogContentList anchors={anchors} />
                  </Wrapper>
                  <Wrapper>
                    <BlogContent content={text} />
                  </Wrapper>
                </>
              ) : (
                <Wrapper>
                  <BlogHeader blog={blog.attributes} />
                  <Divider className={styles.customLineColor} />
                  <BlogContent content={text} />
                </Wrapper>
              )}
            </Col>
            {!isMobile && (
              <Col size={3}>
                <Wrapper>
                  <BlogContentList anchors={anchors} />
                </Wrapper>
              </Col>
            )}
          </Flex>
        </Container>
        <Space isMobile={isMobile} />
      </Container>
    </Layout>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  try {
    const { slug } = context.query;

    const [navigation, blog, footerInfo] = await Promise.all([
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/navigation"),
      axios.get(
        `${process.env.NEXT_PUBLIC_APP_BASEURL}/api/blogs?filters[slug][$eq]=${slug}&populate=*`
      ),
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/footer"),
    ]);

    return {
      props: {
        footerInfo: footerInfo.data,
        navigation: navigation.data,
        blog: blog.data,
      },
    };
  } catch (error) {
    return;
  }
}

const Space = styled.div<{ isMobile: boolean }>`
  height: ${(props) => (props.isMobile ? "20px" : "200px")};
  background-image: ${(props) =>
    props.isMobile ? "initial" : "url(images/lines.png)"};
  margin: ${tokens.spacingVerticalXXXL} 0;
}
`;

const Wrapper = styled.div`
  border-radius: ${tokens.borderRadiusXLarge};
  background: ${tokens.colorNeutralBackground2};
  padding: ${tokens.spacingVerticalXXL};
}
`;

const useStyles = makeStyles({
  customLineColor: {
    "::before": {
      ...shorthands.borderColor(tokens.colorNeutralBackground2Pressed),
    },
    "::after": {
      ...shorthands.borderColor(tokens.colorNeutralBackground2Pressed),
    },
    marginTop: tokens.spacingVerticalXXL,
  },
  img: {
    ...shorthands.borderRadius(tokens.spacingVerticalS),
  },
  readDuration: {
    color: tokens.colorNeutralForeground4,
    fontFamily: "YekanBakhFaNum",
  },
});
