import ButtonFullWidth from "@/components/Common/Button/ButtonBlock";
import Container from "@/components/Common/Container";
import Col from "@/components/Common/Grid/Col";
import Flex from "@/components/Common/Grid/Flex";
import { IndeterminateBar } from "@/components/Common/Progress/IndeterminateBar";
import Layout from "@/components/Layouts/Layout";
import tokens from "@/config/tokens";
import useDocumentation from "@/hooks/useDocumentation";
import {
  Accordion,
  AccordionHeader,
  AccordionItem,
  AccordionPanel,
  Body1,
  Button,
  makeStyles,
  shorthands,
} from "@fluentui/react-components";
import { ChevronDownIcon } from "@heroicons/react/24/outline";
import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import styled from "styled-components";

type Props = {
  footerInfo: FooterInfo;
  navigation: Menu[];
  menu: DocumentationMenu[];
};

export default function Documentation(props: Props) {
  const { footerInfo, navigation, menu } = props;
  const [slug, setSlug] = useState("/getting-started");
  const styles = useStyles();

  const { data, isLoading, isFetching, refetch } = useDocumentation(slug);

  return (
    <Layout footerInfo={footerInfo} navigation={navigation}>
      <Head>
        <title>داکیومنت</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <Container>
        {/* <Heading title="بلاگ" /> */}
        <Flex style={{ padding: `${tokens.spacingVerticalXXXL} 0` }}>
          <Col size={3}>
            <Accordion collapsible multiple className={styles.accordion}>
              {menu.map(({ attributes: menuItem, id }) => {
                return menuItem.subMenu ? (
                  <AccordionItem key={`doc-menu-${id}`} value={id}>
                    <AccordionHeader
                      className={styles.accordionHeader}
                      expandIconPosition="end"
                      expandIcon={<ChevronDownIcon width={12} />}
                    >
                      {menuItem.title}
                    </AccordionHeader>
                    <AccordionPanel className={styles.accordionPanel}>
                      <Flex column className={styles.menuWrapper} gap={16}>
                        <Menu>
                          {menuItem.subMenu.map((item, index) => (
                            <Body1 key={`menu-${id}-item-${index}`}>
                              <MenuItem
                                appearance="transparent"
                                size="small"
                                onClick={() => {
                                  setSlug(item.slug);
                                  refetch();
                                }}
                              >
                                {item.title}
                              </MenuItem>
                            </Body1>
                          ))}
                        </Menu>
                      </Flex>
                    </AccordionPanel>
                  </AccordionItem>
                ) : (
                  <Button
                    key={`doc-menu-${id}`}
                    appearance="subtle"
                    size="large"
                    style={{ height: "44px" }}
                    className={styles.buttonItem}
                  >
                    <Body1>{menuItem.title}</Body1>
                  </Button>
                );
              })}
            </Accordion>
          </Col>
          <Col size={9}>
            {isLoading || isFetching ? (
              <IndeterminateBar />
            ) : data.length ? (
              <Pre>{data[0].attributes.text}</Pre>
            ) : (
              "محتوایی یافت نشد !"
            )}
          </Col>
        </Flex>
      </Container>
    </Layout>
  );
}

export async function getServerSideProps() {
  try {
    const [navigation, menu, footerInfo] = await Promise.all([
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/navigation"),
      axios.get(
        process.env.NEXT_PUBLIC_APP_BASEURL + "/api/documentation/menu"
      ),
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/footer-info"),
    ]);

    return {
      props: {
        menu: menu.data,
        navigation: navigation.data,
        footerInfo: footerInfo.data,
      },
    };
  } catch (error) {
    return;
  }
}

const useStyles = makeStyles({
  copyWrite: {
    color: tokens.colorNeutralForeground4,
  },
  logoCaption: {
    color: tokens.colorNeutralForeground4,
  },
  link: {
    backgroundColor: tokens.colorNeutralBackground3Selected,
    ...shorthands.borderRadius(tokens.spacingVerticalSNudge),
    height: "36px",
    width: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  accordion: {
    display: "flex",
    flexDirection: "column",
    rowGap: tokens.spacingVerticalMNudge,
    maxHeight: "600px",
    position: "sticky",
    top: "10px",
    ...shorthands.overflow("auto"),
    "::-webkit-scrollbar": {
      width: "4px",
    },
    "::-webkit-scrollbar-thumb": {
      backgroundColor: tokens.colorNeutralForeground4,
      ...shorthands.borderRadius(tokens.borderRadiusMedium),
    },
    "&:before": {
      content: '""',
      backgroundImage:
        "linear-gradient(0deg, #141414 0%, rgba(20, 20, 20, 0) 100%)",
      height: "100px",
      width: "100%",
      position: "absolute",
      bottom: 0,
    },
  },
  buttonItem: {
    justifyContent: "flex-start",
  },
  accordionPanel: {
    marginTop: tokens.spacingVerticalXL,
    ...shorthands.margin(
      tokens.spacingVerticalXL,
      0,
      0,
      tokens.spacingVerticalXL
    ),
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    borderRightColor: "currentColor",
  },
  accordionHeader: {
    "> button": {
      ...shorthands.borderRadius(tokens.borderRadiusMedium),
    },
    "> button:hover": {
      backgroundColor: tokens.colorSubtleBackgroundHover,
      color: tokens.colorNeutralForeground2Hover,
    },
    "> button[aria-expanded='true'] > span > svg": {
      transform: "rotate(-180deg)",
    },
  },
  menuWrapper: {
    marginBottom: tokens.spacingVerticalXXXL,
  },
});

const Pre = styled.pre`
  white-space: break-spaces;
  font-family: "YekanBakh";
  line-height: 2rem;
`;

const Menu = styled.div`
  display: flex;
  flex-direction: column;
  gap: ${tokens.spacingVerticalXS};
`;
const MenuItem = styled(ButtonFullWidth)`
  justify-content: flex-start !important;
  height: 44px !important;
  padding: 0 ${tokens.spacingVerticalXL} !important;
`;
