import BlogCard from "@/components/Blog/BlogCard";
import Container from "@/components/Common/Container";
import Flex from "@/components/Common/Grid/Flex";
import Heading from "@/components/Common/Pack/Heading";
import Hero from "@/components/Home/Hero";
import Layout from "@/components/Layouts/Layout";
import { tokens } from "@fluentui/react-components";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import brainstormPic from "../public/images/brainstorm.png";
import brainstormMobilePic from "../public/images/brainstorm-m.png";
import useIsMobile from "@/hooks/useIsMobile";
import { Swiper, SwiperSlide } from "swiper/react";
import { Swiper as SwiperType } from "swiper";
import { Navigation, Pagination } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { useRef, useState } from "react";
import { ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/20/solid";

type Props = {
  footerInfo: FooterInfo;
  hero: Hero;
  navigation: Menu[];
  blogs: Blog[];
  brainstorm: Brainstorm;
};

export default function Home(props: Props) {
  const { footerInfo, hero, navigation, brainstorm, blogs } = props;
  const isMobile = useIsMobile();
  const swiperRef = useRef<SwiperType>();
  const [activeIndex, setActiveIndex] = useState(0);
  const updateActiveIndex = (swiperInstance: SwiperType) => {
    if (swiperInstance === null) return;
    const currentSlide = swiperInstance?.activeIndex;
    setActiveIndex(currentSlide);
  };
  return (
    <Layout footerInfo={footerInfo} navigation={navigation}>
      <Head>
        <title>Protopie</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <Container>
        <Hero data={hero} />
        <Brainstorm
          column
          align="center"
          justify="center"
          gap={tokens.spacingHorizontalMNudge}
          isMobile={isMobile}
        >
          <Heading title={brainstorm?.title} subtitle={brainstorm?.subTitle} />
          {isMobile ? (
            <Image
              src={brainstormMobilePic}
              alt="Brainstorm"
              style={{ padding: "1rem" }}
              loading="lazy"
              placeholder="blur"
            />
          ) : (
            <Image
              src={brainstormPic}
              alt="Brainstorm"
              loading="lazy"
              placeholder="blur"
            />
          )}
        </Brainstorm>
        <Flex column align="center" justify="center">
          <Heading title="بلاگ" subtitle="نکات آموزشی، اخبار، ترفند و ..." />

          <Swiper
            onBeforeInit={(swiper) => {
              swiperRef.current = swiper;
            }}
            dir="rtl"
            slidesPerView={isMobile ? "auto" : 4}
            centeredSlides={isMobile}
            modules={[Navigation, Pagination]}
            onActiveIndexChange={updateActiveIndex}
          >
            {blogs.map((blog, index) => (
              <SwiperSlide key={`blog-${index}`}>
                <BlogCard {...blog} />
              </SwiperSlide>
            ))}
          </Swiper>
          {(isMobile || blogs.length > 4) && (
            <Flex gap={tokens.spacingVerticalS} justify="center" align="center">
              <ChevronRightIcon
                width={32}
                height={32}
                onClick={() => swiperRef.current?.slidePrev()}
              />
              {blogs.map((blog, index) => (
                <CircleIcon
                  key={`blog-dot-${index}`}
                  isCurrent={index === activeIndex}
                  onClick={() => swiperRef.current?.slideTo(index)}
                />
              ))}
              <ChevronLeftIcon
                width={32}
                height={32}
                onClick={() => swiperRef.current?.slideNext()}
              />
            </Flex>
          )}
        </Flex>
        <Space isMobile={isMobile} />
      </Container>
    </Layout>
  );
}

export async function getServerSideProps() {
  try {
    const [homepage, blogs, navigation, footerInfo] = await Promise.all([
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/homepage"),
      axios.get(
        process.env.NEXT_PUBLIC_APP_BASEURL +
          "/api/blogs?fields[0]=title&fields[1]=readDuration&populate=*&fields[2]=slug&fields[3]=category_id&fields[4]=image&pagination[page]=1&pagination[pageSize]=4"
      ),
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/navigation"),
      axios.get(process.env.NEXT_PUBLIC_APP_BASEURL + "/api/footer"),
    ]);

    return {
      props: {
        ...homepage.data,
        footerInfo: footerInfo.data,
        navigation: navigation.data,
        blogs: blogs.data,
      },
    };
  } catch (error) {
    return;
  }
}

const CircleIcon = styled.i<{ isCurrent: boolean }>`
  width: ${(props) => (props.isCurrent ? "8px" : "3px")};
  height: ${(props) => (props.isCurrent ? "8px" : "3px")};
  background-color: ${(props) =>
    props.isCurrent
      ? tokens.colorBrandForeground1
      : tokens.colorNeutralForeground2};
  border-radius: 50%;
`;
const Brainstorm = styled(Flex)<{ isMobile: boolean }>`
  padding: ${tokens.spacingVerticalXXXL}, 0px, ${tokens.spacingVerticalXXXL},
    0px;
  height: 625px;
  background-image: ${(props) =>
    props.isMobile ? "initial" : "url(images/lines-bg.png)"};
  background-repeat: no-repeat;
  background-size: auto;
  background-position: center;
`;

const Space = styled.div<{ isMobile: boolean }>`
  height: ${(props) => (props.isMobile ? "20px" : "200px")};
  background-image: ${(props) =>
    props.isMobile ? "initial" : "url(images/lines.png)"};
  margin: ${tokens.spacingVerticalXXXL} 0;
}
`;
